# Site settings
title: Federal Identity, Credential, and Access Management Architecture
name: Federal Identity, Credential, and Access Management Architecture
email: icam@gsa.gov
author:
    name: FICAM
description: Information on the US FICAM Architecture
baseurl: '/ficam-arch'
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  gsa
highlighter: rouge
branch: staging

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /ficam-arch/img/logo.png
logoalt: Federal Identity Credential and Access Management

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: ficam-arch
  description: FICAM Architecture
  url: https://github.com/GSA/ficam-arch/

# Put the information about your site's GitHub repository if it is public
repo_url: https://github.com/GSA/ficam-arch/
  
# Build settings
markdown: kramdown

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

navigation:
- text: Introduction
  url: ''
  internal: true
  coll: false
- text: Background
  url: background
  internal: true
  coll: false
- text: Conceptual View
  url: conceptual
  internal: true
  coll: false
- text: Goals and Objectives
  url: goals
  internal: true
  coll: false
- text: Services Framework
  url: services/
  internal: true
  coll: true
  collname: services
- text: Use Cases
  url: usecases/
  internal: true
  coll: true
  collname: usecases
- text: Applications View
  url: applications
  internal: true
  coll: false
#- text: Demos
#  url: demos/index/
#  internal: true
#  coll: true
#  collname: usecases
#https://github.com/jekyll/jekyll/issues/2346
#- text: FAQ
#  url: faq
#  internal: true
#  coll: false
- text: Standards & Policies
  url: standards
  internal: true
  coll: false
- text: Contribute
  url: contribute
  internal: true
  coll: false

#https://github.com/jekyll/jekyll/issues/2346
collections:
  usecases:
    label: "Use Cases"
    permalink: usecases/:path/
    output: true
  services:
    label: "Services"
    permalink: services/:path/
    output: true

#- text: Update the config file
#  url: update-the-config-file/
#  internal: true
#  children:
#  - text: Understanding the `baseurl:` property
#    url: understanding-baseurl/
#    internal: true

include:
- _stylesheets
- _javascript



# Custom site configuration
lang: en
